### ISSUE TITLE
독후감 작성 시 이미지 업로드 기능 추가

### ISSUE THREAD

**Issue by donkeeman** [FE-Ocean/who-be-go#9]
## 추가 기능 설명
독후감 작성 시 이미지 업로드 기능 추가

## 할 일
- [x] 이미지 선택 시 진짜 이미지 파일인지 자바스크립트로 한 번 더 검사 (아닌 경우 alert 출력하기)
- [x] 이미지 선택 시 독후감 텍스트 위에 보이게 하기
- [x] 이미지 업로드는 3개까지 제한

**Comment by waterbinnn** [comment]
확인했습니다 고생하셨어요 !
